// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqtsphaxawkpkhcxtlln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdHNwaGF4YXdrcGtoY3h0bGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODg2MDAsImV4cCI6MjA2Mzg2NDYwMH0.JkbVNPOTnMHVJP9V1-xoOCBR0pkJ4Tt6un0vpAaK0qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);